import { Lecture } from "./types";

// 광주·전남 지역 무료강연 샘플 데이터
// 실제 운영 시 공공데이터포털 API 응답으로 교체됩니다 (lib/api.ts 참고)
export const sampleLectures: Lecture[] = [
  {
    id: "1",
    title: "AI 시대, 우리는 무엇을 준비해야 하는가",
    description:
      "인공지능이 바꾸는 일상과 직업의 변화를 살펴보고, 평범한 시민이 준비할 수 있는 디지털 역량을 안내하는 대중 강연입니다.",
    organization: "광주광역시 평생교육진흥원",
    region: "광주 서구",
    category: "IT/디지털",
    venue: "광주시민회관 대강당",
    startDate: "2026-07-04",
    endDate: "2026-07-04",
    startTime: "14:00",
    capacity: 200,
    applyUrl: "https://www.gjlll.or.kr",
    contact: "062-123-4567",
    isFree: true,
    source: "광주광역시 평생교육진흥원",
  },
  {
    id: "2",
    title: "노후를 위한 똑똑한 자산관리",
    description:
      "은퇴를 앞둔 시민을 위한 연금, 투자, 부동산 기초 강의. 금융 전문가가 알기 쉽게 설명합니다.",
    organization: "전라남도 일자리경제진흥원",
    region: "전남 기타",
    category: "재테크/경제",
    venue: "전남도청 김대중강당",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    startTime: "10:00",
    capacity: 150,
    applyUrl: "https://www.jepa.kr",
    contact: "061-987-6543",
    isFree: true,
    source: "전라남도",
  },
  {
    id: "3",
    title: "고전에서 배우는 삶의 지혜",
    description:
      "논어와 맹자를 현대적으로 풀어내는 인문학 강연. 매주 토요일 4주간 진행됩니다.",
    organization: "순천시립도서관",
    region: "전남 순천시",
    category: "인문학",
    venue: "순천기적의도서관",
    startDate: "2026-07-05",
    endDate: "2026-07-26",
    startTime: "15:00",
    capacity: 50,
    applyUrl: "https://lib.suncheon.go.kr",
    contact: "061-749-8800",
    isFree: true,
    source: "순천시",
  },
  {
    id: "4",
    title: "건강한 노년을 위한 생활 운동",
    description:
      "관절에 무리 없는 스트레칭과 근력 운동을 배우는 실습형 건강 강좌입니다.",
    organization: "여수시보건소",
    region: "전남 여수시",
    category: "건강/의료",
    venue: "여수시민체육관",
    startDate: "2026-07-08",
    endDate: "2026-07-08",
    startTime: "10:30",
    capacity: 40,
    contact: "061-659-4000",
    isFree: true,
    source: "여수시",
  },
  {
    id: "5",
    title: "1인 창업, 무엇부터 시작할까",
    description:
      "예비 창업자를 위한 사업자등록, 세무, 마케팅 기초를 다루는 실무 강연.",
    organization: "광주광역시 소상공인종합지원센터",
    region: "광주 북구",
    category: "취업/창업",
    venue: "광주창조경제혁신센터",
    startDate: "2026-07-15",
    endDate: "2026-07-15",
    startTime: "19:00",
    capacity: 60,
    applyUrl: "https://www.gjsbdc.or.kr",
    contact: "062-360-0500",
    isFree: true,
    source: "광주광역시",
  },
  {
    id: "6",
    title: "우리 아이 마음 읽기 - 부모 교육",
    description:
      "아동 심리 전문가와 함께하는 부모를 위한 자녀 소통법 강연입니다.",
    organization: "나주시건강가정지원센터",
    region: "전남 나주시",
    category: "육아/가정",
    venue: "나주시청 대회의실",
    startDate: "2026-07-12",
    endDate: "2026-07-12",
    startTime: "10:00",
    capacity: 80,
    contact: "061-333-2333",
    isFree: true,
    source: "나주시",
  },
  {
    id: "7",
    title: "사진으로 기록하는 우리 동네",
    description:
      "스마트폰 사진 촬영 기법과 지역 사진 아카이빙을 배우는 문화예술 강좌.",
    organization: "목포문화재단",
    region: "전남 목포시",
    category: "문화/예술",
    venue: "목포시민문화체육센터",
    startDate: "2026-07-18",
    endDate: "2026-07-18",
    startTime: "14:00",
    capacity: 30,
    applyUrl: "https://www.mokpoart.com",
    contact: "061-270-8400",
    isFree: true,
    source: "목포시",
  },
  {
    id: "8",
    title: "디지털 사기 예방 - 어르신을 위한 안전 교육",
    description:
      "보이스피싱, 스미싱 등 디지털 금융 사기를 예방하는 실용 강연입니다.",
    organization: "광양시평생학습관",
    region: "전남 광양시",
    category: "IT/디지털",
    venue: "광양읍 평생학습관",
    startDate: "2026-07-09",
    endDate: "2026-07-09",
    startTime: "14:00",
    capacity: 50,
    contact: "061-797-3500",
    isFree: true,
    source: "광양시",
  },
  {
    id: "9",
    title: "대나무 고장에서 배우는 우리 생태 이야기",
    description:
      "죽녹원과 함께하는 지역 생태·환경 강연. 가족 단위 참여가 가능한 무료 프로그램입니다.",
    organization: "담양군 평생학습센터",
    region: "전남 담양군",
    category: "문화/예술",
    venue: "담양군민회관",
    startDate: "2026-07-11",
    endDate: "2026-07-11",
    startTime: "10:00",
    capacity: 60,
    contact: "061-380-3114",
    isFree: true,
    source: "담양군",
  },
  {
    id: "10",
    title: "귀농·귀촌, 성공적으로 정착하기",
    description:
      "장성으로 귀농·귀촌을 준비하는 분들을 위한 영농 기초와 정착 지원제도 안내 강연입니다.",
    organization: "장성군 농업기술센터",
    region: "전남 장성군",
    category: "취업/창업",
    venue: "장성군 농업기술센터 대강당",
    startDate: "2026-07-16",
    endDate: "2026-07-16",
    startTime: "14:00",
    capacity: 50,
    contact: "061-390-7600",
    isFree: true,
    source: "장성군",
  },
  {
    id: "11",
    title: "[도서관강좌] 그림책으로 만나는 인문학",
    description:
      "광주 시민을 위한 그림책 읽기 모임. 그림책을 매개로 삶의 질문을 나누는 도서관 인문 프로그램입니다.",
    organization: "광주광역시립무등도서관",
    region: "광주 북구",
    category: "인문학",
    venue: "무등도서관 다목적실",
    startDate: "2026-07-07",
    endDate: "2026-07-28",
    startTime: "10:30",
    capacity: 25,
    applyUrl: "https://mudeung.gjlib.or.kr",
    contact: "062-510-1700",
    isFree: true,
    source: "광주광역시립무등도서관",
  },
  {
    id: "12",
    title: "[도서관강좌] 시니어 스마트폰 사진교실",
    description:
      "도서관에서 진행하는 어르신 대상 스마트폰 사진 촬영·편집 강좌입니다. 4주 과정.",
    organization: "순천기적의도서관",
    region: "전남 순천시",
    category: "IT/디지털",
    venue: "순천기적의도서관 강의실",
    startDate: "2026-07-14",
    endDate: "2026-08-04",
    startTime: "14:00",
    capacity: 20,
    contact: "061-749-8851",
    isFree: true,
    source: "순천시립도서관",
  },
  {
    id: "13",
    title: "[도서관강좌] 어린이 독서논술 교실",
    description:
      "목포 지역 초등학생을 위한 독서논술 프로그램. 책을 읽고 생각을 글로 표현하는 힘을 기릅니다.",
    organization: "목포시립도서관",
    region: "전남 목포시",
    category: "인문학",
    venue: "목포시립도서관 세미나실",
    startDate: "2026-07-19",
    endDate: "2026-08-09",
    startTime: "10:00",
    capacity: 15,
    applyUrl: "https://lib.mokpo.go.kr",
    contact: "061-270-8730",
    isFree: true,
    source: "목포시립도서관",
  },
];
